sudo: false
language: node_js
before_install:
  - npm i postmark-cli -g
node_js:
  - '10'
deploy:
  provider: script
  script: POSTMARK_SERVER_TOKEN=$SERVER_TOKEN postmark templates push ./templates -f
  on:
    branch: master
after_deploy:
  - POSTMARK_SERVER_TOKEN=$SERVER_TOKEN postmark email raw -f=$FROM -t=$TO --subject="Templates pushed" --text="Templates were pushed to Postmark.\r\n\r\n$TRAVIS_BUILD_WEB_URL"
