sudo: false
language: node_js
node_js:
  - '10'
before_deploy:
  - npm i postmark-cli -g
deploy:
  provider: script
  script: POSTMARK_SERVER_TOKEN=$SERVER_TOKEN postmark templates push ./templates -f
  on:
    branch: master
after_deploy:
  provider: script
  script: POSTMARK_SERVER_TOKEN=$SERVER_TOKEN postmark email raw -f=$FROM -t=$TO --subject="Templates pushed!" --text="$TRAVIS_JOB_WEB_URL\n$TRAVIS_BUILD_WEB_URL"
