language: node_js
node_js:
  - "lts/*"
before_deploy:
  - npm i postmark-cli -g
deploy:
  provider: script
  script: postmark templates push ./templates -f
  on:
    branch: master
after_deploy:
  - postmark email raw -f=$FROM -t=$TO --subject="[Travis CI] Templates pushed" --text="Templates have been pushed to Postmark - $TRAVIS_BUILD_WEB_URL"
