sudo: false
language: node_js
before_install:
  - npm i postmark-cli -g
node_js:
  - '10'
deploy:
  provider: script
  script: POSTMARK_SERVER_TOKEN=$SERVER_TOKEN postmark templates push ./templates -c=false
  on:
    branch: master
