sudo: false
language: node_js
before_install:
  - npm i postmark-cli -g
node_js:
  - 'lts/*'
  - '10'
  - '9'
  - '8'
  - '7'
  - node
deploy:
  provider: script
  script: POSTMARK_SERVER_TOKEN=$SERVER_TOKEN postmark templates push ./templates
  on:
    branch: master
